[package]
name = "helium-core"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bytemuck.workspace = true
pollster.workspace = true
tracing.workspace = true
winit.workspace = true
wgpu.workspace = true
